---
dependency:
  name: galaxy

#driver:
#  name: docker

driver:
  name: podman

#platforms:
#  - name: claranet_gitlab_runner_${name:-${image:-debian}-${tag:-latest}-${scenario:-default}
#    image: ${image:-debian}:${tag:-latest}
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    privileged: true
    tty: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    stop_signal: "SIGRTMIN+3"
    capabilities:
      - SYS_ADMIN
      - SYS_TIME
      - LINUX_IMMUTABLE
    command: "/lib/systemd/systemd"

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
  options:
    v: true

verifier:
  name: testinfra
lint:
  name: flake8
  options:
  verbose: true
  s: true

lint: |
  set -e
  yamllint .
  ansible-lint
